import type { Metadata } from 'next';
import { aspireLogo } from '../logo';
import styles from '../legal.module.css';

export const metadata: Metadata = {
  title: 'Privacy Policy — Aspire 101',
  description: 'How Aspire 101 collects, uses, shares, and protects information.'
};

const toc = [
  ['intro','Introduction'],['collect','Information we collect'],['payments','Payments & payouts'],['moderation','Automated safety'],['location','Location data'],['reputation','Reputation & reviews'],['use','How we use information'],['share','How we share information'],['cookies','Cookies & local storage'],['security','Security'],['retention','Retention'],['rights','Your choices & rights'],['children','Age requirements'],['changes','Changes'],['contact','Contact']
];

export default function PrivacyPage(){
  return <div className={styles.page}>
    <header className={styles.header}><div className={styles.headerInner}>
      <a className={styles.brand} href="/"><img src={aspireLogo} alt=""/><span>Aspire 101</span></a>
      <nav className={styles.nav}><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/guidelines">Guidelines</a><a className={styles.cta} href="/signup">Join Aspire</a></nav>
    </div></header>

    <main className={styles.main}>
      <section className={styles.hero}>
        <div><p className={styles.eyebrow}>LEGAL · ASPIRE 101</p><h1>Privacy<br/>Policy.</h1></div>
        <div className={styles.heroMeta}><p><strong>Last updated:</strong> September 8, 2026</p><p>Aspire is a campus network for requests, matching, messaging, reputation, marketplace transactions, and protected payments. This policy explains what information is handled by Aspire and what is handled directly by service providers such as Stripe.</p></div>
      </section>

      <div className={styles.content}>
        <nav className={styles.toc}>{toc.map(([id,label],i)=><a key={id} href={`#${id}`}>{String(i+1).padStart(2,'0')} · {label}</a>)}</nav>
        <article className={styles.doc}>
          <section id="intro" className={styles.section}><h2>1. Introduction</h2><p>Aspire 101 (“Aspire,” “we,” “us”) provides a college-focused request, matching, marketplace, messaging, and payment-enabled platform. This Privacy Policy applies to our website, app, and related services and should be read with our <a href="/terms">Terms of Service</a> and <a href="/guidelines">Community Guidelines</a>.</p><div className={styles.callout}><strong>Privacy principle:</strong> Aspire is designed so highly sensitive payment and payout fields can be collected directly by specialized payment providers instead of being stored in Aspire&apos;s application database.</div></section>

          <section id="collect" className={styles.section}><h2>2. Information we collect</h2><ul><li><strong>Account and campus information:</strong> name or nickname, university email, school, campus identifiers, profile details, avatar, authentication status, and account-security information.</li><li><strong>Request and marketplace activity:</strong> requests, listings, responses, saves, categories, prices or budgets, timestamps, market intent, order/connection status, and completion information.</li><li><strong>Messages and interactions:</strong> private connection messages, reports, support submissions, dispute descriptions, collaboration proposals, and related metadata.</li><li><strong>Reputation and safety information:</strong> reviews, experience tags, completion counts, account status, moderation results, trust/risk signals, reports, blocks, and enforcement history.</li><li><strong>Payment records held by Aspire:</strong> transaction amounts, fee snapshots, currency, Stripe-generated identifiers, checkout/payment status, payout-readiness status, transfer/refund/dispute identifiers, and reconciliation records.</li><li><strong>Technical information:</strong> browser/device information, language, IP address, timestamps, diagnostics, security logs, and anti-abuse signals.</li><li><strong>Optional submissions:</strong> information you intentionally provide to support, partnership, ambassador, or collaboration features.</li></ul></section>

          <section id="payments" className={styles.section}><h2>3. Payments & payouts</h2><p>Aspire currently uses Stripe to provide payment processing, embedded checkout, connected-account onboarding, and payouts. Stripe may collect payment-card data, bank-account information, legal name, date of birth, address, tax information, and other identity or compliance information directly through Stripe-hosted or Stripe-embedded components.</p><div className={styles.callout}><strong>Aspire does not intend to receive or store your full card number, card security code (CVC), or raw bank-account credentials entered in Stripe components.</strong></div><ul><li>Aspire may receive and store limited Stripe identifiers and status information needed to know whether a payment succeeded, whether a seller is payout-ready, and whether a transfer, refund, dispute, or chargeback occurred.</li><li>We may store transaction amounts, platform-fee calculations, payout/release state, and historical fee snapshots for support, accounting, fraud prevention, dispute handling, and legal recordkeeping.</li><li>Stripe processes information under its own privacy policy and legal obligations. Stripe may request additional verification information when required by financial, banking, card-network, or regulatory rules.</li><li>Payment information may be retained by Stripe independently of Aspire according to Stripe&apos;s policies and applicable law.</li></ul></section>

          <section id="moderation" className={styles.section}><h2>4. Automated safety & content review</h2><p>Aspire uses automated systems to help evaluate user-generated content and platform risk. This can include names, profile photos, request/listing text and images, responses, messages, review notes, and behavioral signals such as duplicate or unusually rapid activity.</p><ul><li>Automated safety checks may use third-party AI or moderation infrastructure, including OpenAI moderation services, to classify text or images for harmful, unsafe, fraudulent, or prohibited content.</li><li>Routine public content may be automatically allowed or blocked before publication based on safety signals and Aspire policy rules.</li><li>We may retain moderation results, risk scores, categories, content hashes, policy flags, and enforcement history to prevent repeat abuse and improve platform safety.</li><li>Reports and dispute submissions may contain descriptions of harmful conduct; we do not treat the mere presence of that language as proof that the reporter violated policy.</li><li>Automated systems can make mistakes. Where appropriate, users may contact support to ask about an account or content decision.</li></ul></section>

          <section id="location" className={styles.section}><h2>5. Location data</h2><p>Aspire can use your location to show nearby requests and make campus discovery more useful. We request browser/device location only after you choose a location-enabled feature or grant permission.</p><ul><li>You can deny location access and use manual campus or city selection instead.</li><li>When precise coordinates are available, they may be used to calculate proximity, distance, or nearby campuses.</li><li>We aim to display approximate location context rather than exposing precise coordinates to other users unless a feature clearly requires and explains it.</li><li>Exact meetup or home addresses should be shared only when a user intentionally provides them in an appropriate private context.</li></ul></section>

          <section id="reputation" className={styles.section}><h2>6. Reputation & reviews</h2><p>Aspire may use one reputation profile per account because the same person can be a requester, buyer, seller, or responder in different interactions. New accounts may appear as “New to Aspire” until enough completed interactions exist to support meaningful trust signals.</p><ul><li>Reputation may include completed-connection counts, ratings, experience tags, account standing, or a “would connect again” type signal.</li><li>Reviews may be withheld until both users submit them or until a review window closes to reduce retaliation.</li><li>Safety reports are handled separately from ordinary ratings and may be visible only to authorized safety or support personnel.</li><li>We may remove, limit, or investigate reviews that appear fraudulent, abusive, retaliatory, or manipulated.</li></ul></section>

          <section id="use" className={styles.section}><h2>7. How we use information</h2><ul><li>Operate accounts, campus verification, profiles, request posting, search, matching, marketplace orders, messaging, reputation, and notifications.</li><li>Process payments, determine payout readiness, calculate fees, coordinate release, issue eligible refunds, reconcile transfers, and respond to payment disputes.</li><li>Protect users, detect scams and abuse, moderate content, investigate reports, enforce platform rules, and reduce fraud or chargeback risk.</li><li>Show relevant requests based on campus, category, search terms, and optional location.</li><li>Respond to support, partnership, ambassador, and collaboration inquiries.</li><li>Improve product performance, safety, and usability using aggregated, statistical, or de-identified information where practical.</li><li>Comply with law, accounting obligations, payment-provider requirements, and enforceable requests from authorities.</li></ul></section>

          <section id="share" className={styles.section}><h2>8. How we share information</h2><p><strong>We do not sell personal information.</strong> We may share information with service providers that perform services for Aspire, such as hosting, database/storage, authentication, email, analytics, maps, security, automated content moderation, payment processing, fraud prevention, and customer support.</p><p>For example, Stripe receives information required to process payments and payouts, and automated moderation providers may receive content submitted for safety analysis. Providers process information under their own contracts, policies, and legal obligations. We may also disclose information when required by law, reasonably necessary to protect users or the platform, or as part of a corporate transaction such as a merger, financing, acquisition, or reorganization.</p><p>Information you intentionally post to public or campus-visible areas, including parts of a profile, listing, request, or reputation signal, may be seen by other users according to the feature&apos;s visibility settings.</p></section>

          <section id="cookies" className={styles.section}><h2>9. Cookies & local storage</h2><p>We may use cookies and browser storage for sign-in sessions, preferences, campus selection, security, fraud prevention, and performance. Embedded service providers may also use technically necessary storage to provide payment or authentication functionality. Blocking certain storage may prevent account or payment features from working correctly.</p></section>

          <section id="security" className={styles.section}><h2>10. Security</h2><p>We use reasonable technical and organizational safeguards, including encrypted connections, access controls, database/storage policies, server-side secret handling, least-privilege permissions, and separation of sensitive payment fields into specialized provider components. No internet service can guarantee perfect security.</p><ul><li>Do not place card numbers, bank credentials, passwords, verification codes, Social Security numbers, or other unnecessary sensitive data into posts or messages.</li><li>Aspire employees and users should never ask you to send a full card number or password through chat.</li><li>If we become aware of a security incident, we will evaluate notification obligations under applicable law.</li></ul></section>

          <section id="retention" className={styles.section}><h2>11. Retention</h2><p>We retain information for as long as reasonably needed to operate Aspire, maintain safety and accounting records, prevent fraud, resolve disputes, and meet legal obligations. Account information is generally kept while an account is active. Some payment, transaction, moderation, safety, dispute, tax, or audit records may be retained after account closure when reasonably necessary or legally required. Third-party providers such as Stripe may maintain their own retention schedules.</p></section>

          <section id="rights" className={styles.section}><h2>12. Your choices & rights</h2><ul><li>Update or correct account information where the product permits.</li><li>Control browser location permission through your device or browser settings.</li><li>Request access to or deletion of personal information where applicable, subject to exceptions for fraud, safety, transaction, tax, accounting, or legal records.</li><li>Withdraw consent for optional processing where consent is the applicable legal basis.</li><li>Exercise additional privacy rights available under applicable state, federal, or international law.</li></ul><p>We may need to verify your identity before completing a privacy request. A request to delete an Aspire account does not automatically delete information independently retained by payment providers under their legal obligations.</p></section>

          <section id="children" className={styles.section}><h2>13. Age requirements</h2><p>Aspire is designed for college communities and is not directed to children. Account and payment eligibility are governed by our Terms of Service, provider requirements, and applicable law.</p></section>

          <section id="changes" className={styles.section}><h2>14. Changes to this policy</h2><p>We may update this policy as Aspire adds features, providers, or legal requirements. When changes are material, we may provide notice in the product, by email, or through another prominent method.</p></section>

          <section id="contact" className={styles.section}><h2>15. Contact</h2><p>Questions about privacy can be sent to <a href="mailto:legal@aspires101.com">legal@aspires101.com</a>.</p></section>
          <p className={styles.note}>This policy describes Aspire&apos;s current beta architecture, including embedded Stripe payments and automated safety systems. It is product-facing legal copy, not a substitute for jurisdiction-specific legal advice; qualified counsel should review final production terms before broad or multi-state launch.</p>
        </article>
      </div>
    </main>
  </div>;
}
