-- Aspire 101 realtime connection chat + My Circle + reconnect review layer.

alter table public.connection_messages
  drop constraint if exists connection_messages_body_length_check;
alter table public.connection_messages
  add constraint connection_messages_body_length_check
  check (char_length(btrim(body)) between 1 and 2000);

create table if not exists public.connection_message_reads (
  connection_id uuid not null references public.connections(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  last_read_message_id bigint null references public.connection_messages(id) on delete set null,
  last_read_at timestamptz not null default now(),
  primary key (connection_id, user_id)
);
create index if not exists connection_message_reads_user_idx on public.connection_message_reads(user_id, last_read_at desc);

create table if not exists public.connection_circle_choices (
  connection_id uuid not null references public.connections(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  keep_in_circle boolean not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (connection_id, user_id)
);
create index if not exists connection_circle_choices_user_idx on public.connection_circle_choices(user_id, updated_at desc);

create table if not exists public.connection_reviews (
  id bigint generated by default as identity primary key,
  connection_id uuid not null references public.connections(id) on delete cascade,
  reviewer_id uuid not null references auth.users(id) on delete cascade,
  reviewee_id uuid not null references auth.users(id) on delete cascade,
  would_connect_again boolean not null,
  tags text[] not null default '{}'::text[],
  note text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (connection_id, reviewer_id),
  check (reviewer_id <> reviewee_id),
  check (note is null or char_length(note) <= 500)
);
create index if not exists connection_reviews_reviewee_idx on public.connection_reviews(reviewee_id, created_at desc);

alter table public.connection_message_reads enable row level security;
alter table public.connection_circle_choices enable row level security;
alter table public.connection_reviews enable row level security;

drop policy if exists "users read own message cursor" on public.connection_message_reads;
create policy "users read own message cursor" on public.connection_message_reads
for select to authenticated using (user_id = auth.uid());

drop policy if exists "connection participants read circle choices" on public.connection_circle_choices;
create policy "connection participants read circle choices" on public.connection_circle_choices
for select to authenticated using (exists (
  select 1 from public.connections c where c.id = connection_circle_choices.connection_id
    and (auth.uid() = c.requester_id or auth.uid() = c.responder_id)
));

drop policy if exists "connection participants read reviews" on public.connection_reviews;
create policy "connection participants read reviews" on public.connection_reviews
for select to authenticated using (exists (
  select 1 from public.connections c where c.id = connection_reviews.connection_id
    and (auth.uid() = c.requester_id or auth.uid() = c.responder_id)
));

create or replace function public.can_message_connection(p_connection_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.connections c
    where c.id = p_connection_id
      and (auth.uid() = c.requester_id or auth.uid() = c.responder_id)
      and (
        c.status in ('confirmed','active')
        or (c.status = 'completed' and exists (
          select 1 from public.connection_circle_choices a
          join public.connection_circle_choices b on b.connection_id = a.connection_id
          where a.connection_id = c.id
            and a.user_id = c.requester_id and a.keep_in_circle = true
            and b.user_id = c.responder_id and b.keep_in_circle = true
        ))
      )
      and not exists (
        select 1 from public.user_blocks ub
        where (ub.blocker_id = c.requester_id and ub.blocked_id = c.responder_id)
           or (ub.blocker_id = c.responder_id and ub.blocked_id = c.requester_id)
      )
  );
$$;
revoke all on function public.can_message_connection(uuid) from public;
grant execute on function public.can_message_connection(uuid) to authenticated;

drop policy if exists "confirmed participants send messages" on public.connection_messages;
drop policy if exists "participants send connection messages" on public.connection_messages;
create policy "allowed connection participants send messages" on public.connection_messages
for insert to authenticated with check (auth.uid() = sender_id and public.can_message_connection(connection_id));

create or replace function public.mark_connection_read(p_connection_id uuid, p_last_message_id bigint default null)
returns bigint language plpgsql security definer set search_path = public as $$
declare v_last bigint;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if not exists (select 1 from public.connections c where c.id = p_connection_id and (auth.uid() = c.requester_id or auth.uid() = c.responder_id)) then raise exception 'Not authorized'; end if;
  if p_last_message_id is null then
    select max(id) into v_last from public.connection_messages where connection_id = p_connection_id;
  else
    select max(id) into v_last from public.connection_messages where connection_id = p_connection_id and id <= p_last_message_id;
  end if;
  insert into public.connection_message_reads(connection_id,user_id,last_read_message_id,last_read_at)
  values (p_connection_id,auth.uid(),v_last,now())
  on conflict (connection_id,user_id) do update set
    last_read_message_id = case
      when public.connection_message_reads.last_read_message_id is null then excluded.last_read_message_id
      when excluded.last_read_message_id is null then public.connection_message_reads.last_read_message_id
      else greatest(public.connection_message_reads.last_read_message_id, excluded.last_read_message_id)
    end,
    last_read_at = now();
  return coalesce(v_last,0);
end;
$$;
revoke all on function public.mark_connection_read(uuid,bigint) from public;
grant execute on function public.mark_connection_read(uuid,bigint) to authenticated;

create or replace function public.get_connection_unread_counts()
returns table(connection_id uuid, unread_count bigint, last_message_at timestamptz)
language sql stable security definer set search_path = public as $$
  select c.id,
    count(m.id) filter (where m.sender_id <> auth.uid() and m.id > coalesce(r.last_read_message_id,0))::bigint,
    max(m.created_at)
  from public.connections c
  left join public.connection_messages m on m.connection_id = c.id
  left join public.connection_message_reads r on r.connection_id = c.id and r.user_id = auth.uid()
  where auth.uid() is not null and (auth.uid() = c.requester_id or auth.uid() = c.responder_id)
  group by c.id,r.last_read_message_id;
$$;
revoke all on function public.get_connection_unread_counts() from public;
grant execute on function public.get_connection_unread_counts() to authenticated;

create or replace function public.set_circle_choice(p_connection_id uuid,p_keep boolean)
returns boolean language plpgsql security definer set search_path = public as $$
declare v_connection public.connections;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  select * into v_connection from public.connections where id = p_connection_id;
  if not found then raise exception 'Connection not found'; end if;
  if auth.uid() <> v_connection.requester_id and auth.uid() <> v_connection.responder_id then raise exception 'Not authorized'; end if;
  if v_connection.status <> 'completed' then raise exception 'Complete the connection before adding someone to your Circle'; end if;
  insert into public.connection_circle_choices(connection_id,user_id,keep_in_circle,updated_at)
  values (p_connection_id,auth.uid(),p_keep,now())
  on conflict (connection_id,user_id) do update set keep_in_circle = excluded.keep_in_circle, updated_at = now();
  return p_keep;
end;
$$;
revoke all on function public.set_circle_choice(uuid,boolean) from public;
grant execute on function public.set_circle_choice(uuid,boolean) to authenticated;

create or replace function public.get_my_circle()
returns table(connection_id uuid,other_user_id uuid,connected_at timestamptz)
language sql stable security definer set search_path = public as $$
  select c.id,
    case when auth.uid() = c.requester_id then c.responder_id else c.requester_id end,
    greatest(a.updated_at,b.updated_at)
  from public.connections c
  join public.connection_circle_choices a on a.connection_id=c.id and a.user_id=c.requester_id and a.keep_in_circle=true
  join public.connection_circle_choices b on b.connection_id=c.id and b.user_id=c.responder_id and b.keep_in_circle=true
  where auth.uid() is not null and c.status='completed'
    and (auth.uid()=c.requester_id or auth.uid()=c.responder_id)
    and not exists (
      select 1 from public.user_blocks ub
      where (ub.blocker_id=c.requester_id and ub.blocked_id=c.responder_id)
         or (ub.blocker_id=c.responder_id and ub.blocked_id=c.requester_id)
    )
  order by greatest(a.updated_at,b.updated_at) desc;
$$;
revoke all on function public.get_my_circle() from public;
grant execute on function public.get_my_circle() to authenticated;

create or replace function public.submit_connection_review(
  p_connection_id uuid,p_would_connect_again boolean,p_tags text[] default '{}'::text[],p_note text default null
)
returns bigint language plpgsql security definer set search_path = public as $$
declare v_connection public.connections; v_reviewee uuid; v_id bigint; v_tags text[];
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  select * into v_connection from public.connections where id=p_connection_id;
  if not found then raise exception 'Connection not found'; end if;
  if auth.uid()<>v_connection.requester_id and auth.uid()<>v_connection.responder_id then raise exception 'Not authorized'; end if;
  if v_connection.status<>'completed' then raise exception 'Complete the connection before reviewing'; end if;
  v_reviewee := case when auth.uid()=v_connection.requester_id then v_connection.responder_id else v_connection.requester_id end;
  select coalesce(array_agg(distinct tag),'{}'::text[]) into v_tags
  from unnest(coalesce(p_tags,'{}'::text[])) tag
  where tag in ('reliable','friendly','on_time','good_communication','helpful');
  insert into public.connection_reviews(connection_id,reviewer_id,reviewee_id,would_connect_again,tags,note,updated_at)
  values (p_connection_id,auth.uid(),v_reviewee,p_would_connect_again,v_tags,nullif(left(btrim(coalesce(p_note,'')),500),''),now())
  on conflict (connection_id,reviewer_id) do update set
    would_connect_again=excluded.would_connect_again,tags=excluded.tags,note=excluded.note,updated_at=now()
  returning id into v_id;
  return v_id;
end;
$$;
revoke all on function public.submit_connection_review(uuid,boolean,text[],text) from public;
grant execute on function public.submit_connection_review(uuid,boolean,text[],text) to authenticated;

create or replace function public.confirm_connection_completion(p_connection_id uuid)
returns integer language plpgsql security definer set search_path=public as $$
declare v_connection public.connections; v_count integer;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  select * into v_connection from public.connections where id=p_connection_id for update;
  if not found then raise exception 'Connection not found'; end if;
  if auth.uid()<>v_connection.requester_id and auth.uid()<>v_connection.responder_id then raise exception 'Not authorized'; end if;
  if v_connection.status not in ('confirmed','active') then raise exception 'Connection is not ready for completion'; end if;
  insert into public.connection_completion_confirmations(connection_id,user_id) values (p_connection_id,auth.uid()) on conflict (connection_id,user_id) do nothing;
  select count(*)::integer into v_count from public.connection_completion_confirmations
    where connection_id=p_connection_id and user_id in (v_connection.requester_id,v_connection.responder_id);
  if v_count>=2 and coalesce(v_connection.payment_method,'none')<>'aspire' then
    update public.connections set status='completed',updated_at=now() where id=p_connection_id;
    update public.requests set status='completed',updated_at=now() where id=v_connection.request_id and status not in ('completed','cancelled');
  end if;
  return v_count;
end;
$$;
revoke all on function public.confirm_connection_completion(uuid) from public;
grant execute on function public.confirm_connection_completion(uuid) to authenticated;

do $$
begin
  if exists (select 1 from pg_publication where pubname='supabase_realtime')
     and not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='connection_messages') then
    alter publication supabase_realtime add table public.connection_messages;
  end if;
end $$;
