-- Aspire 101 persistent notification center.

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null check (kind in ('request_response','connection_chosen','connection_confirmed','connection_completed','connection_cancelled','message','circle_mutual')),
  actor_id uuid null references auth.users(id) on delete set null,
  request_id uuid null references public.requests(id) on delete set null,
  response_id uuid null references public.request_responses(id) on delete set null,
  connection_id uuid null references public.connections(id) on delete set null,
  message_id bigint null references public.connection_messages(id) on delete set null,
  event_key text not null,
  title text not null check (char_length(title) between 1 and 140),
  body text null check (body is null or char_length(body) <= 360),
  read_at timestamptz null,
  created_at timestamptz not null default now(),
  unique (user_id, event_key)
);

create index if not exists notifications_user_created_idx on public.notifications(user_id, created_at desc);
create index if not exists notifications_user_unread_idx on public.notifications(user_id, created_at desc) where read_at is null;

alter table public.notifications enable row level security;

drop policy if exists "users read own notifications" on public.notifications;
create policy "users read own notifications" on public.notifications
for select to authenticated using (user_id = auth.uid());

revoke all on public.notifications from anon;
revoke insert, update, delete on public.notifications from authenticated;
grant select on public.notifications to authenticated;

create or replace function public.push_notification(
  p_user_id uuid,
  p_kind text,
  p_event_key text,
  p_title text,
  p_body text default null,
  p_actor_id uuid default null,
  p_request_id uuid default null,
  p_response_id uuid default null,
  p_connection_id uuid default null,
  p_message_id bigint default null
)
returns bigint language plpgsql security definer set search_path = public as $$
declare v_id bigint;
begin
  if p_user_id is null or p_event_key is null or btrim(p_event_key) = '' then return null; end if;
  insert into public.notifications(user_id,kind,actor_id,request_id,response_id,connection_id,message_id,event_key,title,body)
  values (
    p_user_id,p_kind,p_actor_id,p_request_id,p_response_id,p_connection_id,p_message_id,
    left(p_event_key,220),left(btrim(p_title),140),nullif(left(btrim(coalesce(p_body,'')),360),'')
  )
  on conflict (user_id,event_key) do nothing
  returning id into v_id;
  return v_id;
end;
$$;
revoke all on function public.push_notification(uuid,text,text,text,text,uuid,uuid,uuid,uuid,bigint) from public;

create or replace function public.mark_notification_read(p_notification_id bigint)
returns boolean language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  update public.notifications set read_at = coalesce(read_at,now()) where id=p_notification_id and user_id=auth.uid();
  return found;
end;
$$;
revoke all on function public.mark_notification_read(bigint) from public;
grant execute on function public.mark_notification_read(bigint) to authenticated;

create or replace function public.mark_all_notifications_read()
returns integer language plpgsql security definer set search_path = public as $$
declare v_count integer;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  update public.notifications set read_at=now() where user_id=auth.uid() and read_at is null;
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;
revoke all on function public.mark_all_notifications_read() from public;
grant execute on function public.mark_all_notifications_read() to authenticated;

create or replace function public.notify_request_response_insert()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_poster uuid; v_title text;
begin
  select poster_id,title into v_poster,v_title from public.requests where id=new.request_id;
  if v_poster is not null and v_poster <> new.responder_id then
    perform public.push_notification(v_poster,'request_response','response:'||new.id::text,'New response to your request',
      coalesce('Someone responded to “'||v_title||'”.','You received a new response.'),new.responder_id,new.request_id,new.id,null,null);
  end if;
  return new;
end;
$$;
revoke all on function public.notify_request_response_insert() from public;
drop trigger if exists notify_request_response_after_insert on public.request_responses;
create trigger notify_request_response_after_insert after insert on public.request_responses
for each row execute function public.notify_request_response_insert();

create or replace function public.notify_connection_change()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_title text; v_actor uuid; v_other uuid;
begin
  select title into v_title from public.requests where id=new.request_id;
  v_actor := auth.uid();
  if tg_op='INSERT' then
    perform public.push_notification(new.responder_id,'connection_chosen','connection-chosen:'||new.id::text,'You were chosen for a request',
      coalesce('Confirm “'||v_title||'” to open private chat.','Confirm the connection to open private chat.'),
      new.requester_id,new.request_id,null,new.id,null);
    return new;
  end if;
  if old.status is distinct from new.status then
    if new.status in ('confirmed','active') and old.status not in ('confirmed','active') then
      perform public.push_notification(new.requester_id,'connection_confirmed','connection-confirmed:'||new.id::text,'Your connection is confirmed',
        coalesce('Private chat is open for “'||v_title||'”.','Private chat is now open.'),new.responder_id,new.request_id,null,new.id,null);
    elsif new.status='completed' and old.status<>'completed' then
      perform public.push_notification(new.requester_id,'connection_completed','connection-completed:'||new.id::text||':'||new.requester_id::text,'Connection completed',
        'You can now leave a trust review and choose whether to keep in touch.',v_actor,new.request_id,null,new.id,null);
      perform public.push_notification(new.responder_id,'connection_completed','connection-completed:'||new.id::text||':'||new.responder_id::text,'Connection completed',
        'You can now leave a trust review and choose whether to keep in touch.',v_actor,new.request_id,null,new.id,null);
    elsif new.status='cancelled' and old.status<>'cancelled' then
      if v_actor=new.requester_id then v_other:=new.responder_id;
      elsif v_actor=new.responder_id then v_other:=new.requester_id;
      else v_other:=new.requester_id; end if;
      perform public.push_notification(v_other,'connection_cancelled','connection-cancelled:'||new.id::text||':'||v_other::text,'A connection was cancelled',
        coalesce('The connection for “'||v_title||'” is no longer active.','This connection is no longer active.'),v_actor,new.request_id,null,new.id,null);
    end if;
  end if;
  return new;
end;
$$;
revoke all on function public.notify_connection_change() from public;
drop trigger if exists notify_connection_after_change on public.connections;
create trigger notify_connection_after_change after insert or update on public.connections
for each row execute function public.notify_connection_change();
