-- Aspire 101 campus marketplace order protection foundation.
-- This models a protected marketplace flow without describing Stripe-held platform funds as legal escrow.

alter table public.requests
  add column if not exists market_intent text,
  add column if not exists item_condition text,
  add column if not exists price_negotiable boolean not null default false,
  add column if not exists fulfillment_method text,
  add column if not exists quantity integer not null default 1;

do $$ begin
  alter table public.requests add constraint requests_market_intent_check
    check (market_intent is null or market_intent in ('sell','wanted'));
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.requests add constraint requests_item_condition_check
    check (item_condition is null or item_condition in ('new','like_new','good','fair','for_parts'));
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.requests add constraint requests_fulfillment_method_check
    check (fulfillment_method is null or fulfillment_method in ('campus_pickup','shipping'));
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.requests add constraint requests_market_quantity_check
    check (quantity between 1 and 99);
exception when duplicate_object then null; end $$;

create table if not exists public.market_orders (
  id uuid primary key default gen_random_uuid(),
  connection_id uuid not null unique references public.connections(id) on delete cascade,
  request_id uuid not null unique references public.requests(id) on delete cascade,
  buyer_id uuid not null references auth.users(id) on delete cascade,
  seller_id uuid not null references auth.users(id) on delete cascade,
  payment_id uuid unique references public.connection_payments(id) on delete set null,
  listing_intent text not null check (listing_intent in ('sell','wanted')),
  fulfillment_method text not null default 'campus_pickup' check (fulfillment_method in ('campus_pickup','shipping')),
  currency text not null default 'USD',
  agreed_amount_cents integer not null check (agreed_amount_cents > 0),
  status text not null default 'awaiting_payment' check (status in (
    'awaiting_payment','payment_processing','paid','handoff_confirmed','release_ready',
    'released','disputed','refunded','cancelled','off_platform'
  )),
  seller_handed_off_at timestamptz,
  buyer_received_at timestamptz,
  dispute_opened_at timestamptz,
  released_at timestamptz,
  refunded_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (buyer_id <> seller_id)
);

create table if not exists public.market_disputes (
  id uuid primary key default gen_random_uuid(),
  market_order_id uuid not null references public.market_orders(id) on delete cascade,
  opened_by uuid not null references auth.users(id) on delete cascade,
  reason text not null check (reason in ('item_not_as_described','item_not_received','counterfeit_or_prohibited','payment_issue','unsafe_handoff','other')),
  details text not null check (char_length(btrim(details)) between 10 and 2000),
  evidence jsonb not null default '[]'::jsonb,
  status text not null default 'open' check (status in ('open','under_review','resolved_buyer','resolved_seller','closed')),
  resolution_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.market_order_events (
  id bigint generated by default as identity primary key,
  market_order_id uuid not null references public.market_orders(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists market_orders_buyer_created_idx on public.market_orders(buyer_id, created_at desc);
create index if not exists market_orders_seller_created_idx on public.market_orders(seller_id, created_at desc);
create index if not exists market_orders_status_idx on public.market_orders(status, updated_at desc);
create index if not exists market_disputes_order_created_idx on public.market_disputes(market_order_id, created_at desc);
create index if not exists market_order_events_order_created_idx on public.market_order_events(market_order_id, created_at desc);

alter table public.market_orders enable row level security;
alter table public.market_disputes enable row level security;
alter table public.market_order_events enable row level security;

grant select on public.market_orders to authenticated;
grant select on public.market_disputes to authenticated;
grant select on public.market_order_events to authenticated;
grant usage, select on sequence public.market_order_events_id_seq to authenticated;
grant all on public.market_orders, public.market_disputes, public.market_order_events to service_role;

drop policy if exists market_orders_participants_read on public.market_orders;
create policy market_orders_participants_read on public.market_orders for select to authenticated
  using (auth.uid() = buyer_id or auth.uid() = seller_id or public.is_admin());

drop policy if exists market_disputes_participants_read on public.market_disputes;
create policy market_disputes_participants_read on public.market_disputes for select to authenticated
  using (exists (
    select 1 from public.market_orders mo
    where mo.id = market_order_id
      and (mo.buyer_id = auth.uid() or mo.seller_id = auth.uid() or public.is_admin())
  ));

drop policy if exists market_order_events_participants_read on public.market_order_events;
create policy market_order_events_participants_read on public.market_order_events for select to authenticated
  using (exists (
    select 1 from public.market_orders mo
    where mo.id = market_order_id
      and (mo.buyer_id = auth.uid() or mo.seller_id = auth.uid() or public.is_admin())
  ));

create or replace function public.ensure_market_order_for_connection()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  r public.requests%rowtype;
  v_buyer uuid;
  v_seller uuid;
  v_amount integer;
  v_status text;
begin
  select * into r from public.requests where id = new.request_id;
  if not found or r.kind <> 'buy_sell' or r.market_intent is null then
    return new;
  end if;

  v_amount := coalesce(new.agreed_amount_cents, r.amount_cents, 0);
  if v_amount <= 0 then return new; end if;

  if r.market_intent = 'sell' then
    v_seller := r.poster_id;
    v_buyer := new.responder_id;
  else
    v_buyer := r.poster_id;
    v_seller := new.responder_id;
  end if;

  v_status := case when coalesce(new.payment_method, r.payment_method, 'none') = 'aspire'
    then 'awaiting_payment' else 'off_platform' end;

  insert into public.market_orders (
    connection_id, request_id, buyer_id, seller_id, listing_intent,
    fulfillment_method, currency, agreed_amount_cents, status
  ) values (
    new.id, r.id, v_buyer, v_seller, r.market_intent,
    coalesce(r.fulfillment_method, 'campus_pickup'), coalesce(r.currency, 'USD'), v_amount, v_status
  )
  on conflict (connection_id) do update set
    buyer_id = excluded.buyer_id,
    seller_id = excluded.seller_id,
    agreed_amount_cents = excluded.agreed_amount_cents,
    fulfillment_method = excluded.fulfillment_method,
    currency = excluded.currency,
    updated_at = now();

  return new;
end;
$$;

drop trigger if exists trg_ensure_market_order_for_connection on public.connections;
create trigger trg_ensure_market_order_for_connection
after insert or update of agreed_amount_cents, payment_method on public.connections
for each row execute function public.ensure_market_order_for_connection();

create or replace function public.sync_market_order_payment_state()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  next_status text;
begin
  if not exists (select 1 from public.market_orders where connection_id = new.connection_id) then
    return new;
  end if;

  next_status := case
    when new.status in ('checkout_created','processing') then 'payment_processing'
    when new.status = 'secured' then 'paid'
    when new.status = 'released' then 'released'
    when new.status = 'disputed' then 'disputed'
    when new.status = 'refunded' then 'refunded'
    when new.status = 'cancelled' then 'cancelled'
    else null
  end;

  update public.market_orders
  set payment_id = new.id,
      status = case
        when next_status is null then status
        when next_status = 'paid' and status in ('handoff_confirmed','release_ready','disputed') then status
        else next_status
      end,
      released_at = case when new.status = 'released' then coalesce(new.released_at, now()) else released_at end,
      refunded_at = case when new.status = 'refunded' then coalesce(new.refunded_at, now()) else refunded_at end,
      dispute_opened_at = case when new.status = 'disputed' then coalesce(new.disputed_at, now()) else dispute_opened_at end,
      updated_at = now()
  where connection_id = new.connection_id;

  return new;
end;
$$;

drop trigger if exists trg_sync_market_order_payment_state on public.connection_payments;
create trigger trg_sync_market_order_payment_state
after insert or update of status, stripe_payment_intent_id, stripe_transfer_id, stripe_refund_id on public.connection_payments
for each row execute function public.sync_market_order_payment_state();

create or replace function public.log_market_order_status_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.market_order_events(market_order_id, actor_id, event_type, payload)
    values (new.id, null, 'order_created', jsonb_build_object('status', new.status));
  elsif old.status is distinct from new.status then
    insert into public.market_order_events(market_order_id, actor_id, event_type, payload)
    values (new.id, auth.uid(), 'status_changed', jsonb_build_object('from', old.status, 'to', new.status));
  end if;
  return new;
end;
$$;

drop trigger if exists trg_log_market_order_status_change on public.market_orders;
create trigger trg_log_market_order_status_change
after insert or update of status on public.market_orders
for each row execute function public.log_market_order_status_change();

create or replace function public.market_mark_handoff(p_connection_id uuid)
returns public.market_orders
language plpgsql
security definer
set search_path = public
as $$
declare
  o public.market_orders;
  p public.connection_payments;
begin
  select * into o from public.market_orders where connection_id = p_connection_id for update;
  if not found then raise exception 'MARKET_ORDER_NOT_FOUND'; end if;
  if auth.uid() is null or auth.uid() <> o.seller_id then raise exception 'NOT_SELLER'; end if;

  select * into p from public.connection_payments where id = o.payment_id;
  if p.id is null or p.status <> 'secured' then raise exception 'PAYMENT_NOT_SECURED'; end if;
  if o.status = 'disputed' then raise exception 'ORDER_DISPUTED'; end if;
  if o.status in ('released','refunded','cancelled') then raise exception 'ORDER_CLOSED'; end if;

  update public.market_orders
  set seller_handed_off_at = coalesce(seller_handed_off_at, now()),
      status = case when buyer_received_at is not null then 'release_ready' else 'handoff_confirmed' end,
      updated_at = now()
  where id = o.id returning * into o;

  insert into public.market_order_events(market_order_id, actor_id, event_type)
  values (o.id, auth.uid(), 'seller_handed_off');
  return o;
end;
$$;

create or replace function public.market_confirm_receipt(p_connection_id uuid)
returns public.market_orders
language plpgsql
security definer
set search_path = public
as $$
declare
  o public.market_orders;
begin
  select * into o from public.market_orders where connection_id = p_connection_id for update;
  if not found then raise exception 'MARKET_ORDER_NOT_FOUND'; end if;
  if auth.uid() is null or auth.uid() <> o.buyer_id then raise exception 'NOT_BUYER'; end if;
  if o.seller_handed_off_at is null then raise exception 'HANDOFF_NOT_CONFIRMED'; end if;
  if o.status = 'disputed' then raise exception 'ORDER_DISPUTED'; end if;
  if o.status in ('released','refunded','cancelled') then raise exception 'ORDER_CLOSED'; end if;

  update public.market_orders
  set buyer_received_at = coalesce(buyer_received_at, now()),
      status = 'release_ready',
      updated_at = now()
  where id = o.id returning * into o;

  insert into public.market_order_events(market_order_id, actor_id, event_type)
  values (o.id, auth.uid(), 'buyer_confirmed_received');
  return o;
end;
$$;

create or replace function public.market_open_dispute(p_connection_id uuid, p_reason text, p_details text)
returns public.market_disputes
language plpgsql
security definer
set search_path = public
as $$
declare
  o public.market_orders;
  d public.market_disputes;
begin
  select * into o from public.market_orders where connection_id = p_connection_id for update;
  if not found then raise exception 'MARKET_ORDER_NOT_FOUND'; end if;
  if auth.uid() is null or (auth.uid() <> o.buyer_id and auth.uid() <> o.seller_id) then raise exception 'NOT_PARTICIPANT'; end if;
  if o.status not in ('paid','handoff_confirmed','release_ready') then raise exception 'DISPUTE_NOT_AVAILABLE'; end if;
  if p_reason not in ('item_not_as_described','item_not_received','counterfeit_or_prohibited','payment_issue','unsafe_handoff','other') then raise exception 'INVALID_DISPUTE_REASON'; end if;
  if char_length(btrim(coalesce(p_details,''))) < 10 then raise exception 'DISPUTE_DETAILS_REQUIRED'; end if;

  if exists (select 1 from public.market_disputes where market_order_id = o.id and status in ('open','under_review')) then
    raise exception 'DISPUTE_ALREADY_OPEN';
  end if;

  insert into public.market_disputes(market_order_id, opened_by, reason, details)
  values (o.id, auth.uid(), p_reason, btrim(p_details)) returning * into d;

  update public.market_orders
  set status = 'disputed', dispute_opened_at = now(), updated_at = now()
  where id = o.id;

  insert into public.market_order_events(market_order_id, actor_id, event_type, payload)
  values (o.id, auth.uid(), 'dispute_opened', jsonb_build_object('dispute_id', d.id, 'reason', p_reason));
  return d;
end;
$$;

revoke all on function public.market_mark_handoff(uuid) from public;
revoke all on function public.market_confirm_receipt(uuid) from public;
revoke all on function public.market_open_dispute(uuid, text, text) from public;
grant execute on function public.market_mark_handoff(uuid) to authenticated;
grant execute on function public.market_confirm_receipt(uuid) to authenticated;
grant execute on function public.market_open_dispute(uuid, text, text) to authenticated;
grant execute on function public.market_mark_handoff(uuid) to service_role;
grant execute on function public.market_confirm_receipt(uuid) to service_role;
grant execute on function public.market_open_dispute(uuid, text, text) to service_role;

comment on table public.market_orders is 'Aspire Protected marketplace order state. Stripe payment and seller transfer are separate; this is not labeled legal escrow.';
comment on column public.requests.market_intent is 'sell = poster is seller; wanted = poster is buyer.';
