-- Aspire Money / transfer ledger foundation.
-- Immutable audit events for protected buyer payments and seller/provider releases.

create table if not exists public.payment_ledger_events (
  id bigint generated by default as identity primary key,
  payment_id uuid not null references public.connection_payments(id) on delete cascade,
  connection_id uuid not null references public.connections(id) on delete cascade,
  request_id uuid not null references public.requests(id) on delete cascade,
  market_order_id uuid references public.market_orders(id) on delete set null,
  payer_id uuid not null references auth.users(id) on delete cascade,
  payee_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (event_type in (
    'checkout_created','payment_processing','payment_secured','payment_failed',
    'transfer_released','payment_refunded','payment_disputed','payment_cancelled'
  )),
  amount_cents integer not null default 0 check (amount_cents >= 0),
  currency text not null default 'USD',
  stripe_object_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists payment_ledger_payment_created_idx
  on public.payment_ledger_events(payment_id, created_at desc);
create index if not exists payment_ledger_payer_created_idx
  on public.payment_ledger_events(payer_id, created_at desc);
create index if not exists payment_ledger_payee_created_idx
  on public.payment_ledger_events(payee_id, created_at desc);
create unique index if not exists payment_ledger_event_dedupe_idx
  on public.payment_ledger_events(payment_id, event_type, coalesce(stripe_object_id, ''));

alter table public.payment_ledger_events enable row level security;
revoke all on public.payment_ledger_events from anon;
grant select on public.payment_ledger_events to authenticated;
grant all on public.payment_ledger_events to service_role;
grant usage, select on sequence public.payment_ledger_events_id_seq to service_role;

drop policy if exists payment_ledger_participant_read on public.payment_ledger_events;
create policy payment_ledger_participant_read
  on public.payment_ledger_events
  for select to authenticated
  using (auth.uid() = payer_id or auth.uid() = payee_id or public.is_admin());

create or replace function public.log_connection_payment_ledger_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event text;
  v_amount integer := 0;
  v_stripe_object text;
  v_market_order_id uuid;
begin
  if tg_op = 'UPDATE' and old.status is not distinct from new.status then
    return new;
  end if;

  v_event := case new.status
    when 'checkout_created' then 'checkout_created'
    when 'processing' then 'payment_processing'
    when 'secured' then 'payment_secured'
    when 'released' then 'transfer_released'
    when 'failed' then 'payment_failed'
    when 'refunded' then 'payment_refunded'
    when 'disputed' then 'payment_disputed'
    when 'cancelled' then 'payment_cancelled'
    else null
  end;

  if v_event is null then return new; end if;

  v_amount := case new.status
    when 'released' then greatest(coalesce(new.provider_net_cents, new.provider_amount_cents, 0), 0)
    when 'secured' then greatest(coalesce(new.customer_total_cents, new.gross_amount_cents, 0), 0)
    when 'refunded' then greatest(coalesce(new.customer_total_cents, new.gross_amount_cents, 0), 0)
    when 'disputed' then greatest(coalesce(new.customer_total_cents, new.gross_amount_cents, 0), 0)
    else greatest(coalesce(new.customer_total_cents, new.gross_amount_cents, 0), 0)
  end;

  v_stripe_object := case new.status
    when 'checkout_created' then new.stripe_checkout_session_id
    when 'processing' then coalesce(new.stripe_payment_intent_id, new.stripe_checkout_session_id)
    when 'secured' then coalesce(new.stripe_charge_id, new.stripe_payment_intent_id)
    when 'released' then new.stripe_transfer_id
    when 'refunded' then new.stripe_refund_id
    when 'disputed' then coalesce(new.stripe_charge_id, new.stripe_payment_intent_id)
    else coalesce(new.stripe_payment_intent_id, new.stripe_checkout_session_id)
  end;

  select id into v_market_order_id
  from public.market_orders
  where connection_id = new.connection_id
  limit 1;

  insert into public.payment_ledger_events (
    payment_id, connection_id, request_id, market_order_id,
    payer_id, payee_id, event_type, amount_cents, currency,
    stripe_object_id, metadata
  ) values (
    new.id, new.connection_id, new.request_id, v_market_order_id,
    new.payer_id, new.payee_id, v_event, v_amount, coalesce(new.currency, 'USD'),
    v_stripe_object,
    jsonb_build_object(
      'payment_status', new.status,
      'fee_policy_version', new.fee_policy_version,
      'base_amount_cents', new.base_amount_cents,
      'customer_total_cents', new.customer_total_cents,
      'provider_net_cents', new.provider_net_cents,
      'platform_fee_cents', new.platform_fee_cents
    )
  ) on conflict do nothing;

  return new;
end;
$$;

revoke all on function public.log_connection_payment_ledger_event() from public, anon, authenticated;
grant execute on function public.log_connection_payment_ledger_event() to service_role;

drop trigger if exists trg_connection_payment_ledger on public.connection_payments;
create trigger trg_connection_payment_ledger
after insert or update of status on public.connection_payments
for each row execute function public.log_connection_payment_ledger_event();

-- Backfill one canonical event for existing terminal/current payment states.
insert into public.payment_ledger_events (
  payment_id, connection_id, request_id, market_order_id,
  payer_id, payee_id, event_type, amount_cents, currency,
  stripe_object_id, metadata, created_at
)
select
  p.id,
  p.connection_id,
  p.request_id,
  mo.id,
  p.payer_id,
  p.payee_id,
  case p.status
    when 'checkout_created' then 'checkout_created'
    when 'processing' then 'payment_processing'
    when 'secured' then 'payment_secured'
    when 'released' then 'transfer_released'
    when 'failed' then 'payment_failed'
    when 'refunded' then 'payment_refunded'
    when 'disputed' then 'payment_disputed'
    when 'cancelled' then 'payment_cancelled'
  end,
  case when p.status = 'released'
    then greatest(coalesce(p.provider_net_cents, p.provider_amount_cents, 0), 0)
    else greatest(coalesce(p.customer_total_cents, p.gross_amount_cents, 0), 0)
  end,
  coalesce(p.currency, 'USD'),
  case p.status
    when 'checkout_created' then p.stripe_checkout_session_id
    when 'processing' then coalesce(p.stripe_payment_intent_id, p.stripe_checkout_session_id)
    when 'secured' then coalesce(p.stripe_charge_id, p.stripe_payment_intent_id)
    when 'released' then p.stripe_transfer_id
    when 'refunded' then p.stripe_refund_id
    when 'disputed' then coalesce(p.stripe_charge_id, p.stripe_payment_intent_id)
    else coalesce(p.stripe_payment_intent_id, p.stripe_checkout_session_id)
  end,
  jsonb_build_object(
    'payment_status', p.status,
    'fee_policy_version', p.fee_policy_version,
    'backfilled', true
  ),
  coalesce(p.updated_at, p.created_at, now())
from public.connection_payments p
left join public.market_orders mo on mo.connection_id = p.connection_id
where p.status in ('checkout_created','processing','secured','released','failed','refunded','disputed','cancelled')
on conflict do nothing;
