-- Privacy-minimized product funnel analytics for the founder growth monitor.
-- Stores only a random browser session id, optional authenticated user id,
-- coarse product surface, named action, and timestamp. No IP/device fingerprint,
-- message content, card data, bank data, or free-form user text is stored.

create table if not exists public.product_analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid null references auth.users(id) on delete set null,
  session_id uuid not null,
  event_name text not null check (event_name in ('page_view','cta_click','signup_submit','signup_success')),
  surface text not null check (surface in ('home','auth','discover','post','inbox','profile','payments','other')),
  target text null check (target is null or (char_length(target) between 1 and 64 and target ~ '^[a-z0-9_:-]+$')),
  created_at timestamptz not null default now()
);

create index if not exists product_analytics_events_created_at_idx on public.product_analytics_events(created_at desc);
create index if not exists product_analytics_events_event_idx on public.product_analytics_events(event_name, created_at desc);
create index if not exists product_analytics_events_session_idx on public.product_analytics_events(session_id, created_at desc);

alter table public.product_analytics_events enable row level security;
revoke all on table public.product_analytics_events from anon, authenticated;
revoke all on sequence public.product_analytics_events_id_seq from anon, authenticated;
grant all on table public.product_analytics_events to service_role;
grant usage, select on sequence public.product_analytics_events_id_seq to service_role;

create or replace function public.record_product_event(
  p_event_name text,
  p_surface text,
  p_target text,
  p_session_id uuid
)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if p_session_id is null then raise exception 'SESSION_REQUIRED'; end if;
  if p_event_name not in ('page_view','cta_click','signup_submit','signup_success') then raise exception 'INVALID_ANALYTICS_EVENT'; end if;
  if p_surface not in ('home','auth','discover','post','inbox','profile','payments','other') then raise exception 'INVALID_ANALYTICS_SURFACE'; end if;
  if p_target is not null and (char_length(p_target) < 1 or char_length(p_target) > 64 or p_target !~ '^[a-z0-9_:-]+$') then raise exception 'INVALID_ANALYTICS_TARGET'; end if;
  insert into public.product_analytics_events(user_id,session_id,event_name,surface,target)
  values(auth.uid(),p_session_id,p_event_name,p_surface,p_target);
end;
$$;

revoke all on function public.record_product_event(text,text,text,uuid) from public;
grant execute on function public.record_product_event(text,text,text,uuid) to anon, authenticated;

create or replace function public.admin_activity_metrics(p_days integer default 30)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_days integer := greatest(7, least(coalesce(p_days,30),90));
  v_today date := (now() at time zone 'utc')::date;
  v_result jsonb;
begin
  if not public.is_admin() then raise exception 'ADMIN_REQUIRED'; end if;

  select jsonb_build_object(
    'generatedAt',now(),'timezone','UTC',
    'todayDau',(select count(*) from public.user_daily_activity a where a.activity_date=v_today),
    'yesterdayDau',(select count(*) from public.user_daily_activity a where a.activity_date=v_today-1),
    'wau',(select count(distinct a.user_id) from public.user_daily_activity a where a.activity_date between v_today-6 and v_today),
    'mau',(select count(distinct a.user_id) from public.user_daily_activity a where a.activity_date between v_today-29 and v_today),
    'newUsersToday',(select count(*) from auth.users u where (u.created_at at time zone 'utc')::date=v_today),
    'totalUsers',(select count(*) from auth.users),
    'verifiedStudents',(select count(*) from auth.users u where u.email_confirmed_at is not null),
    'postsToday',(select count(*) from public.requests r where (r.created_at at time zone 'utc')::date=v_today),
    'responsesToday',(select count(*) from public.request_responses rr where (rr.created_at at time zone 'utc')::date=v_today),
    'connectionsToday',(select count(*) from public.connections c where (c.created_at at time zone 'utc')::date=v_today),
    'paymentsToday',(select count(*) from public.connection_payments cp where cp.paid_at is not null and (cp.paid_at at time zone 'utc')::date=v_today),
    'successfulTransactionsToday',(select count(*) from public.connection_payments cp where cp.paid_at is not null and (cp.paid_at at time zone 'utc')::date=v_today and cp.status in ('secured','released')),
    'processedVolumeCentsToday',coalesce((select sum(cp.customer_total_cents) from public.connection_payments cp where cp.paid_at is not null and (cp.paid_at at time zone 'utc')::date=v_today),0),
    'gmvCentsToday',coalesce((select sum(cp.base_amount_cents) from public.connection_payments cp where cp.paid_at is not null and (cp.paid_at at time zone 'utc')::date=v_today and cp.status in ('secured','released')),0),
    'platformFeeRevenueCentsToday',coalesce((select sum(cp.platform_fee_cents) from public.connection_payments cp where cp.paid_at is not null and (cp.paid_at at time zone 'utc')::date=v_today and cp.status in ('secured','released')),0),
    'takeRateBpsToday',coalesce((select case when sum(cp.base_amount_cents)>0 then round((sum(cp.platform_fee_cents)::numeric/sum(cp.base_amount_cents)::numeric)*10000)::integer else 0 end from public.connection_payments cp where cp.paid_at is not null and (cp.paid_at at time zone 'utc')::date=v_today and cp.status in ('secured','released')),0),
    'payoutsReleasedToday',(select count(*) from public.connection_payments cp where cp.released_at is not null and (cp.released_at at time zone 'utc')::date=v_today),
    'uniqueSessionsToday',(select count(distinct e.session_id) from public.product_analytics_events e where e.event_name='page_view' and (e.created_at at time zone 'utc')::date=v_today),
    'pageViewsToday',(select count(*) from public.product_analytics_events e where e.event_name='page_view' and (e.created_at at time zone 'utc')::date=v_today),
    'trackedClicksToday',(select count(*) from public.product_analytics_events e where e.event_name='cta_click' and (e.created_at at time zone 'utc')::date=v_today),
    'uniqueClickSessionsToday',(select count(distinct e.session_id) from public.product_analytics_events e where e.event_name='cta_click' and (e.created_at at time zone 'utc')::date=v_today),
    'clickThroughRateBpsToday',coalesce((select case when count(distinct e.session_id) filter(where e.event_name='page_view')>0 then round((count(distinct e.session_id) filter(where e.event_name='cta_click')::numeric/count(distinct e.session_id) filter(where e.event_name='page_view')::numeric)*10000)::integer else 0 end from public.product_analytics_events e where (e.created_at at time zone 'utc')::date=v_today),0),
    'signupViewsToday',(select count(distinct e.session_id) from public.product_analytics_events e where e.event_name='page_view' and e.surface='auth' and e.target='signup' and (e.created_at at time zone 'utc')::date=v_today),
    'signupStartsToday',(select count(distinct e.session_id) from public.product_analytics_events e where e.event_name='signup_submit' and (e.created_at at time zone 'utc')::date=v_today),
    'signupCompletionsToday',(select count(distinct e.session_id) from public.product_analytics_events e where e.event_name='signup_success' and (e.created_at at time zone 'utc')::date=v_today),
    'signupRateBpsToday',coalesce((select case when count(distinct e.session_id) filter(where e.event_name='page_view' and e.surface='auth' and e.target='signup')>0 then round((count(distinct e.session_id) filter(where e.event_name='signup_success')::numeric/count(distinct e.session_id) filter(where e.event_name='page_view' and e.surface='auth' and e.target='signup')::numeric)*10000)::integer else 0 end from public.product_analytics_events e where (e.created_at at time zone 'utc')::date=v_today),0),
    'topClicksToday',(select coalesce(jsonb_agg(jsonb_build_object('target',x.target,'clicks',x.clicks,'uniqueSessions',x.unique_sessions) order by x.clicks desc,x.target),'[]'::jsonb) from (select coalesce(e.target,'other') target,count(*) clicks,count(distinct e.session_id) unique_sessions from public.product_analytics_events e where e.event_name='cta_click' and (e.created_at at time zone 'utc')::date=v_today group by coalesce(e.target,'other') order by count(*) desc limit 12)x),
    'daily',(
      select coalesce(jsonb_agg(jsonb_build_object(
        'date',d.day,
        'dau',(select count(*) from public.user_daily_activity a where a.activity_date=d.day),
        'signups',(select count(*) from auth.users u where (u.created_at at time zone 'utc')::date=d.day),
        'posts',(select count(*) from public.requests r where (r.created_at at time zone 'utc')::date=d.day),
        'responses',(select count(*) from public.request_responses rr where (rr.created_at at time zone 'utc')::date=d.day),
        'connections',(select count(*) from public.connections c where (c.created_at at time zone 'utc')::date=d.day),
        'payments',(select count(*) from public.connection_payments cp where cp.paid_at is not null and (cp.paid_at at time zone 'utc')::date=d.day),
        'processedVolumeCents',coalesce((select sum(cp.customer_total_cents) from public.connection_payments cp where cp.paid_at is not null and (cp.paid_at at time zone 'utc')::date=d.day),0),
        'uniqueSessions',(select count(distinct e.session_id) from public.product_analytics_events e where e.event_name='page_view' and (e.created_at at time zone 'utc')::date=d.day),
        'pageViews',(select count(*) from public.product_analytics_events e where e.event_name='page_view' and (e.created_at at time zone 'utc')::date=d.day),
        'clicks',(select count(*) from public.product_analytics_events e where e.event_name='cta_click' and (e.created_at at time zone 'utc')::date=d.day),
        'ctrBps',coalesce((select case when count(distinct e.session_id) filter(where e.event_name='page_view')>0 then round((count(distinct e.session_id) filter(where e.event_name='cta_click')::numeric/count(distinct e.session_id) filter(where e.event_name='page_view')::numeric)*10000)::integer else 0 end from public.product_analytics_events e where (e.created_at at time zone 'utc')::date=d.day),0),
        'signupViews',(select count(distinct e.session_id) from public.product_analytics_events e where e.event_name='page_view' and e.surface='auth' and e.target='signup' and (e.created_at at time zone 'utc')::date=d.day),
        'signupStarts',(select count(distinct e.session_id) from public.product_analytics_events e where e.event_name='signup_submit' and (e.created_at at time zone 'utc')::date=d.day),
        'signupCompletions',(select count(distinct e.session_id) from public.product_analytics_events e where e.event_name='signup_success' and (e.created_at at time zone 'utc')::date=d.day),
        'signupRateBps',coalesce((select case when count(distinct e.session_id) filter(where e.event_name='page_view' and e.surface='auth' and e.target='signup')>0 then round((count(distinct e.session_id) filter(where e.event_name='signup_success')::numeric/count(distinct e.session_id) filter(where e.event_name='page_view' and e.surface='auth' and e.target='signup')::numeric)*10000)::integer else 0 end from public.product_analytics_events e where (e.created_at at time zone 'utc')::date=d.day),0)
      ) order by d.day),'[]'::jsonb) from generate_series(v_today-(v_days-1),v_today,interval '1 day') d(day)
    ),
    'campusesToday',(select coalesce(jsonb_agg(jsonb_build_object('campusId',x.campus_id,'campus',x.campus_name,'shortName',x.short_name,'dau',x.dau) order by x.dau desc,x.campus_name),'[]'::jsonb) from (select p.home_campus_id campus_id,coalesce(u.name,p.school,'Unknown campus') campus_name,coalesce(u.short_name,p.school,'Unknown') short_name,count(*) dau from public.user_daily_activity a join public.profiles p on p.id=a.user_id left join public.universities u on u.id=p.home_campus_id where a.activity_date=v_today group by p.home_campus_id,u.name,u.short_name,p.school order by count(*) desc limit 12)x),
    'campusRegistrations',(select coalesce(jsonb_agg(jsonb_build_object('campus',x.campus,'users',x.users) order by x.users desc,x.campus),'[]'::jsonb) from (select coalesce(u2.short_name,p.school,'Unknown') campus,count(*) users from auth.users u left join public.profiles p on p.id=u.id left join public.universities u2 on u2.id=p.home_campus_id group by coalesce(u2.short_name,p.school,'Unknown') order by count(*) desc limit 20)x),
    'recentUsers',(select coalesce(jsonb_agg(jsonb_build_object('email',x.email,'displayName',x.display_name,'school',x.school,'createdAt',x.created_at,'emailConfirmed',x.email_confirmed) order by x.created_at desc),'[]'::jsonb) from (select u.email,coalesce(p.display_name,p.full_name,p.name) display_name,coalesce(u2.short_name,p.school) school,u.created_at,(u.email_confirmed_at is not null) email_confirmed from auth.users u left join public.profiles p on p.id=u.id left join public.universities u2 on u2.id=p.home_campus_id order by u.created_at desc limit 20)x)
  ) into v_result;
  return v_result;
end;
$$;
