-- Aspire Live Connection foundation: agreed schedule, lightweight status events,
-- and opt-in time-limited location sharing for confirmed connections.

alter table public.connections
  add column if not exists scheduled_start_at timestamptz,
  add column if not exists scheduled_end_at timestamptz,
  add column if not exists timezone text,
  add column if not exists meeting_label text,
  add column if not exists coordination_status text not null default 'planning',
  add column if not exists last_coordination_actor_id uuid references auth.users(id) on delete set null,
  add column if not exists last_coordination_at timestamptz;

alter table public.connections
  drop constraint if exists connections_coordination_status_check;
alter table public.connections
  add constraint connections_coordination_status_check
  check (coordination_status in ('planning','scheduled','on_the_way','arrived','in_progress'));

alter table public.connections
  drop constraint if exists connections_meeting_label_length_check;
alter table public.connections
  add constraint connections_meeting_label_length_check
  check (meeting_label is null or char_length(meeting_label) <= 240);

create table if not exists public.connection_events (
  id bigint generated by default as identity primary key,
  connection_id uuid not null references public.connections(id) on delete cascade,
  actor_id uuid null references auth.users(id) on delete set null,
  event_type text not null check (event_type in ('schedule_set','on_the_way','arrived','in_progress','location_shared','location_stopped','reminder')),
  body text not null check (char_length(body) between 1 and 500),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists connection_events_connection_idx on public.connection_events(connection_id, created_at desc);

create table if not exists public.connection_live_locations (
  connection_id uuid not null references public.connections(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  accuracy_meters double precision null check (accuracy_meters is null or accuracy_meters >= 0),
  expires_at timestamptz not null,
  updated_at timestamptz not null default now(),
  primary key (connection_id, user_id)
);
create index if not exists connection_live_locations_expiry_idx on public.connection_live_locations(expires_at);

alter table public.connection_events enable row level security;
alter table public.connection_live_locations enable row level security;

grant select on public.connection_events to authenticated;
grant select on public.connection_live_locations to authenticated;
grant usage, select on sequence public.connection_events_id_seq to authenticated;

drop policy if exists "connection participants read coordination events" on public.connection_events;
create policy "connection participants read coordination events"
on public.connection_events for select to authenticated using (
  exists (
    select 1 from public.connections c
    where c.id = connection_events.connection_id
      and (auth.uid() = c.requester_id or auth.uid() = c.responder_id)
  )
);

drop policy if exists "connection participants read active shared location" on public.connection_live_locations;
create policy "connection participants read active shared location"
on public.connection_live_locations for select to authenticated using (
  expires_at > now()
  and exists (
    select 1 from public.connections c
    where c.id = connection_live_locations.connection_id
      and c.status in ('confirmed','active')
      and (auth.uid() = c.requester_id or auth.uid() = c.responder_id)
  )
);

create or replace function public.set_connection_schedule(
  p_connection_id uuid,
  p_start_at timestamptz,
  p_timezone text,
  p_meeting_label text default null,
  p_end_at timestamptz default null
)
returns void language plpgsql security definer set search_path = public as $$
declare
  v_connection public.connections;
  v_label text;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if p_start_at is null then raise exception 'Start time required'; end if;
  if p_end_at is not null and p_end_at <= p_start_at then raise exception 'End time must be after start time'; end if;

  select * into v_connection from public.connections where id = p_connection_id for update;
  if not found then raise exception 'Connection not found'; end if;
  if auth.uid() <> v_connection.requester_id and auth.uid() <> v_connection.responder_id then raise exception 'Not authorized'; end if;
  if v_connection.status not in ('confirmed','active') then raise exception 'Connection is not ready for scheduling'; end if;

  v_label := nullif(left(btrim(coalesce(p_meeting_label,'')),240),'');

  update public.connections set
    scheduled_start_at = p_start_at,
    scheduled_end_at = p_end_at,
    timezone = nullif(left(btrim(coalesce(p_timezone,'')),100),''),
    meeting_label = v_label,
    coordination_status = 'scheduled',
    last_coordination_actor_id = auth.uid(),
    last_coordination_at = now(),
    updated_at = now()
  where id = p_connection_id;

  insert into public.connection_events(connection_id,actor_id,event_type,body,metadata)
  values (
    p_connection_id,
    auth.uid(),
    'schedule_set',
    case when v_label is null then 'Meeting time updated.' else 'Meeting time and place updated.' end,
    jsonb_build_object('scheduled_start_at',p_start_at,'scheduled_end_at',p_end_at,'timezone',p_timezone,'meeting_label',v_label)
  );
end;
$$;
revoke all on function public.set_connection_schedule(uuid,timestamptz,text,text,timestamptz) from public;
grant execute on function public.set_connection_schedule(uuid,timestamptz,text,text,timestamptz) to authenticated;

create or replace function public.set_connection_coordination_status(
  p_connection_id uuid,
  p_status text
)
returns void language plpgsql security definer set search_path = public as $$
declare
  v_connection public.connections;
  v_body text;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if p_status not in ('on_the_way','arrived','in_progress') then raise exception 'Invalid coordination status'; end if;

  select * into v_connection from public.connections where id = p_connection_id for update;
  if not found then raise exception 'Connection not found'; end if;
  if auth.uid() <> v_connection.requester_id and auth.uid() <> v_connection.responder_id then raise exception 'Not authorized'; end if;
  if v_connection.status not in ('confirmed','active') then raise exception 'Connection is not active'; end if;

  v_body := case p_status
    when 'on_the_way' then 'On the way.'
    when 'arrived' then 'Arrived at the meeting point.'
    else 'Task started.'
  end;

  update public.connections set
    status = case when status = 'confirmed' then 'active' else status end,
    coordination_status = p_status,
    last_coordination_actor_id = auth.uid(),
    last_coordination_at = now(),
    updated_at = now()
  where id = p_connection_id;

  insert into public.connection_events(connection_id,actor_id,event_type,body)
  values (p_connection_id,auth.uid(),p_status,v_body);
end;
$$;
revoke all on function public.set_connection_coordination_status(uuid,text) from public;
grant execute on function public.set_connection_coordination_status(uuid,text) to authenticated;

create or replace function public.share_connection_location(
  p_connection_id uuid,
  p_latitude double precision,
  p_longitude double precision,
  p_accuracy_meters double precision default null,
  p_minutes integer default 30
)
returns timestamptz language plpgsql security definer set search_path = public as $$
declare
  v_connection public.connections;
  v_expires timestamptz;
  v_minutes integer;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if p_latitude not between -90 and 90 or p_longitude not between -180 and 180 then raise exception 'Invalid coordinates'; end if;

  select * into v_connection from public.connections where id = p_connection_id;
  if not found then raise exception 'Connection not found'; end if;
  if auth.uid() <> v_connection.requester_id and auth.uid() <> v_connection.responder_id then raise exception 'Not authorized'; end if;
  if v_connection.status not in ('confirmed','active') then raise exception 'Location can only be shared for an active connection'; end if;

  v_minutes := greatest(5,least(coalesce(p_minutes,30),120));
  v_expires := now() + make_interval(mins => v_minutes);

  insert into public.connection_live_locations(connection_id,user_id,latitude,longitude,accuracy_meters,expires_at,updated_at)
  values (p_connection_id,auth.uid(),p_latitude,p_longitude,p_accuracy_meters,v_expires,now())
  on conflict (connection_id,user_id) do update set
    latitude = excluded.latitude,
    longitude = excluded.longitude,
    accuracy_meters = excluded.accuracy_meters,
    expires_at = excluded.expires_at,
    updated_at = now();

  insert into public.connection_events(connection_id,actor_id,event_type,body,metadata)
  values (p_connection_id,auth.uid(),'location_shared','Shared live location temporarily.',jsonb_build_object('expires_at',v_expires));

  return v_expires;
end;
$$;
revoke all on function public.share_connection_location(uuid,double precision,double precision,double precision,integer) from public;
grant execute on function public.share_connection_location(uuid,double precision,double precision,double precision,integer) to authenticated;

create or replace function public.stop_connection_location_share(p_connection_id uuid)
returns void language plpgsql security definer set search_path = public as $$
declare
  v_connection public.connections;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  select * into v_connection from public.connections where id = p_connection_id;
  if not found then raise exception 'Connection not found'; end if;
  if auth.uid() <> v_connection.requester_id and auth.uid() <> v_connection.responder_id then raise exception 'Not authorized'; end if;

  delete from public.connection_live_locations where connection_id = p_connection_id and user_id = auth.uid();
  insert into public.connection_events(connection_id,actor_id,event_type,body)
  values (p_connection_id,auth.uid(),'location_stopped','Stopped sharing live location.');
end;
$$;
revoke all on function public.stop_connection_location_share(uuid) from public;
grant execute on function public.stop_connection_location_share(uuid) to authenticated;
