-- In-app reminders for scheduled Aspire Live connections.
-- Delivery is generated by the authenticated Vercel cron route; this migration only
-- extends the notification/event schema and keeps duplicate reminder runs idempotent.

alter table public.notifications
  drop constraint if exists notifications_kind_check;
alter table public.notifications
  add constraint notifications_kind_check
  check (kind in (
    'request_response',
    'connection_chosen',
    'connection_confirmed',
    'connection_completed',
    'connection_cancelled',
    'message',
    'circle_mutual',
    'connection_reminder'
  ));

alter table public.connection_events
  add column if not exists event_key text;

create unique index if not exists connection_events_event_key_unique_idx
  on public.connection_events(event_key)
  where event_key is not null;

alter table public.connection_events
  drop constraint if exists connection_events_event_key_length_check;
alter table public.connection_events
  add constraint connection_events_event_key_length_check
  check (event_key is null or char_length(event_key) <= 220);
