export default function MarketplaceRulesPage() {
  return (
    <main className="legalPage">
      <div className="legalShell">
        <a className="legalBack" href="/">← Aspire 101</a>
        <p className="eyebrow">ASPIRE MARKET</p>
        <h1>Marketplace &amp; Order Protection Rules</h1>
        <p className="legalLead">These rules explain the beta flow for permitted physical goods exchanged through Aspire 101. They supplement the Terms, Community Guidelines, and Privacy Policy.</p>

        <section><h2>1. Physical goods beta</h2><p>Aspire Market currently supports permitted physical goods between verified campus users. Do not list stolen goods, counterfeit goods, regulated or prohibited items, weapons, drugs, prescription products, account credentials, access codes, hacked or compromised accounts, or anything you do not have the right to sell.</p></section>
        <section><h2>2. Be accurate</h2><p>Sellers must accurately describe condition, defects, included accessories, quantity, and material facts that could affect a buyer&apos;s decision. Photos should show the actual item when you are selling an item you already possess.</p></section>
        <section><h2>3. Interest is not a charge</h2><p>Selecting “I&apos;m interested” sends one interest response to the seller. It does not charge the buyer, reserve funds, create multiple purchases when clicked again, or guarantee that the seller will choose that buyer. A payment step can begin only after the marketplace connection reaches the transaction state required by Aspire.</p></section>
        <section><h2>4. Aspire Protected</h2><p>When an eligible order uses Pay with Aspire, Stripe processes the buyer&apos;s payment through Stripe components embedded in the Aspire experience. Aspire does not receive or store the buyer&apos;s full card number or CVC. Aspire records limited transaction identifiers, amounts, fees, and status needed to operate the order-protection workflow.</p><p>After a successful charge, Aspire records the payment as secured and delays the separate seller transfer until the applicable handoff/receipt and release conditions are satisfied. “Secured” is an Aspire transaction status; Aspire Protected is not represented as a bank account, stored-value wallet, or legal escrow service.</p></section>
        <section><h2>5. Campus handoff</h2><p>Campus pickup is the supported fulfillment method in this beta. Meet in a sensible public location, inspect the item before confirming receipt, and do not mark an item received until you actually have it and have had a reasonable chance to inspect it.</p></section>
        <section><h2>6. Cancellation &amp; refunds</h2><p>Before the seller marks handoff, a secured Aspire payment may be eligible for cancellation and refund through the protected order flow. After handoff begins, users should report a problem instead of using instant cancellation. Refund timing and availability can also depend on Stripe, card-network, bank, fraud-review, and transaction-state rules.</p></section>
        <section><h2>7. Problems &amp; disputes</h2><p>A buyer or seller can report issues such as an item not being received, an item materially not matching its description, prohibited or counterfeit goods, payment issues, duplicate transaction concerns, or an unsafe handoff. Opening an eligible Aspire order dispute pauses seller release while the order is reviewed. Card-network disputes and chargebacks are handled under applicable Stripe and payment-network processes and may continue even after an apparent payment or payout.</p></section>
        <section><h2>8. Off-platform payments</h2><p>Cash, Venmo, Zelle, external payment links, cryptocurrency, or other payments made outside Pay with Aspire are not processed or protected as Aspire payments. Users should never be pressured to move an Aspire-protected transaction off-platform to bypass fees, safety controls, or the transaction record.</p></section>
        <section><h2>9. Seller payouts</h2><p>Sellers using Aspire Protected must complete the required Stripe payout onboarding. Stripe directly handles the sensitive banking, identity, tax, and compliance fields required for payouts; Aspire stores limited payout-readiness and transaction metadata rather than raw bank credentials. The amount shown as seller earnings is the sale amount minus the applicable Aspire platform fee. Payout availability and timing can also be affected by Stripe, banks, compliance requirements, risk reviews, refunds, reserves, and disputes.</p></section>
        <section><h2>10. Retry &amp; duplicate protection</h2><p>Aspire uses transaction identifiers and idempotency controls so ordinary retries, double-clicks, duplicate webhook delivery, or temporary network errors should not intentionally create duplicate interest records, charges, or seller transfers. Users should still check the visible order/payment status before retrying a financial action and report any unexpected duplicate transaction immediately.</p></section>
        <section><h2>11. Enforcement</h2><p>Aspire may remove listings, pause marketplace privileges, restrict accounts, preserve relevant platform records, and review reports when reasonably necessary for trust, safety, fraud prevention, payment risk, legal compliance, or enforcement of these rules.</p></section>
        <section><h2>12. Contact</h2><p>For marketplace or business issues that require human follow-up, contact business@aspires101.com. Privacy questions can be sent to legal@aspires101.com.</p></section>
      </div>
    </main>
  );
}
